import { Swiper, SwiperSlide } from "swiper/react";
import { roadMapProps } from "../sliderProps";
const RoadMapSlider = () => {
  return (
    <section id="roadmap">
      <div className="container">
        <h3
          className="fn__maintitle big"
          data-text="Event Timeline"
          data-align="center"
        >
          Event Timeline
        </h3>
        <div className="fn_cs_roadmap">
          <div className="step_holder">
            <div className="step_in" />
          </div>
          <div className="slider_holder">
            <Swiper {...roadMapProps} className="swiper-container">
              <div className="swiper-wrapper">
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 01</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">QR Code Quest CSE</h3>
                      <p className="desc">
                      QR Code Quest is a thrilling treasure hunt activity in which users scan QR codes posted in various places to uncover hints and work out riddles.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 02</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">Roboterry ECE</h3>
                      <p className="desc">
                      RoboTerry is a thrilling and exciting robotics event inspired by the popular cartoon characters Tom and Jerry.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 03</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">Scriptify IT</h3>
                      <p className="desc">
                      The Scriptify is a fun and challenging event that helps participants improve their coding and typing skills while also testing their ability to perform under pressure.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 04</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">Chem-e-Car CHEMICAL</h3>
                      <p className="desc">
                      Chem-e-car is an exciting competition where participants are required to create a car whose propulsion is driven by an exothermic reaction, or electricity, which is generated by the chemical reaction occurring inside the car.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 05</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">Hurdle Mania MECHANICAL</h3>
                      <p className="desc">
                      Hurdle Mania is one of the most awaited events of Mechatronic. The main task in the event is to construct a racing bot (wired/wireless).
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 06</span>
                    <div className="item_in">
                      <p className="date">31.03.2023</p>
                      <h3 className="title">RoboSoccer CHEMICAL + ECE</h3>
                      <p className="desc">
                      Introducing RoboSoccer event based on Football. Design a Soccer-bot with a pushing or hitting mechanism and score as many goals as you can.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 07</span>
                    <div className="item_in">
                      <p className="date">01.04.2023</p>
                      <h3 className="title">Ergo genius IPE-</h3>
                      <p className="desc">
                      Product Design with Ergonomics and Life Cycle Assessment Challenge. It’s objective is to design a product that prioritizes ergonomics and sustainability.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 08</span>
                    <div className="item_in">
                      <p className="date">01.04.2023</p>
                      <h3 className="title">Culvert CIVIL</h3>
                      <p className="desc">
                      Culvert CIVIL- Create a culvert out of a limited number of ice-cream sticks and glue. Make it bearable to lift some load in order to check its potential. Stronger and stable the foundation the nearer you get towards victory.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
                <SwiperSlide className="swiper-slide">
                  <div className="item">
                    <span className="icon" />
                    <span className="phase">Major Event 09</span>
                    <div className="item_in">
                      <p className="date">01.04.2023</p>
                      <h3 className="title">Valorant GAMING</h3>
                      <p className="desc">
                      Valorant is a team-based first-person tactical hero shooter set in the near future. Players play as one of a set of Agents, characters based on several countries and cultures around the world.
                      </p>
                      <a
                        href="https://linktr.ee/EQUILIBRIO23"
                        className="metaportal_fn_button event-button"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <span>Register Now </span>
                      </a>
                    </div>
                  </div>
                </SwiperSlide>
              </div>
            </Swiper>
          </div>
        </div>
      </div>
    </section>
  );
};
export default RoadMapSlider;
